global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: healthcheck
    metrics_path: /metrics
    static_configs:
      - targets:
          - healthcheck:8080

  - job_name: queue_proxy
    metrics_path: /metrics
    static_configs:
      - targets:
          - queue-proxy:4100
